### ISSUE TITLE
Azaya Outreachy Contributions.

### ISSUE THREAD

**Issue by Azaya89** [bokeh/outreach-programs#23]
This is my initial submission for the project: **_Create a blog post series: "Fundamentals of Data Visualization in Bokeh"_** #2 

I created a blog post [here](https://azaya89.github.io/) where I am continually updating it with more visualisations. Some feedback will be appreciated.

**Comment by Azaya89** [comment]
Here is my submission for the micro-task: "**_Explore NYC taxi trips dataset_**" #6

https://github.com/Azaya89/Bokeh-microtask

**Comment by pavithraes** [comment]
@Azaya89 Thanks for sharing! I'd like to acknowledge that this satisfies the microtasks, and we'll share more detailed feedback soon. :)

**Comment by Azaya89** [comment]
> @Azaya89 Thanks for sharing! I'd like to acknowledge that this satisfies the microtasks, and we'll share more detailed feedback soon. :)

Thank you> I await the more detailed feedback.

**Comment by Azaya89** [comment]
Here is my Initial micro-task submission for the Project: **Improve Bokeh's documentation using the Diátaxis framework.** #1

**Setting up a development environment**

![image](https://user-images.githubusercontent.com/99359668/227522352-69ec1d7d-f38d-4c4b-8b8f-16ce6afef630.png)

![image](https://user-images.githubusercontent.com/99359668/227522690-accdb134-c005-4c95-9cb7-cea080f20fc4.png)

**Comment by Azaya89** [comment]
Here is a list of all the PRs raised for the second microtask: **Work on "Add metadata to standalone examples"** #5

This includes both merged and unmerged pull requests.

- [x] https://github.com/bokeh/bokeh/pull/13003
- [x] https://github.com/bokeh/bokeh/pull/13006
- [x] https://github.com/bokeh/bokeh/pull/13012
- [x] https://github.com/bokeh/bokeh/pull/13023
- [ ]  https://github.com/bokeh/bokeh/pull/13019 (Collaborated on an Identical PR instead)
- [ ] https://github.com/bokeh/bokeh/pull/13000 (Declined due to an earlier PR by someone else)

**Comment by pavithraes** [comment]
@Azaya89 Thanks for your all your contributions, your NYC taxi exploration notebook looks fantastic! I think your notebook is well presented, your code is well structure and documented, and overall it's complete. ✨

I have a couple of quick thoughts
- Your pie charts in section 3 and 5 can be color-matched because they depict related data, you can also consider showing them in a single plot/layout if you'd like to
- Since you have created a new repository for your submission (I appreciate you including the dataset sample in the repo!), you can consider adding an `environment.yml` or `requirements.txt` file that list the libraries and versions you used. This is a good practice for data science projects and makes your work more reproducible.

Note that these are fully optional, and I think you have a strong submission as is. :)

I also enjoyed reading your blog post, do make sure to include it in your Outreachy application. Honestly, I don't think you need another review, please feel free to make any updates you see fit and add it to your application. I'm happy to mark your microtask completed!

**Comment by Azaya89** [comment]
Thank you very much. I have color-matched the pie charts, added an `environment.yml` file and also updated my `README` file to reflect the additions.
